name: get-key
on: push
env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: ubuntu-latest
        env:
            API_KEY: ${{ secrets.API_KEY }}
