name: get-key
on: push
env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
      - run: node -e "console.log(process.env.API_KEY)"
        env:
            API_KEY: ${{ secrets.API_KEY }}
